version: '2'
services:
  tmp:
      image: busybox
      command: chmod -R 777 /tmp/docker
      volumes:
          - /tmp/docker/
  php:
    image: yiisoftware/yii2-php:7.1-apache
    container_name: g-api-app
    volumes:
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      - ./:/app:delegated
    volumes_from:
        - tmp
    ports:
      - '80:80'
    networks:
      - skynet
  redis:
      image: redis
      container_name: g-api-redis
      command: redis-server /etc/redis.conf
      volumes:
          - ./redis/redis.conf:/etc/redis.conf
      volumes_from:
          - tmp
  db:
    image: mysql
    container_name: g-api-db
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      - ~/mysql/:/var/lib/mysql
    networks:
      - skynet
    environment:
      MYSQL_ROOT_PASSWORD: root
networks:
    skynet:
        external:
            name: skynet