version: '2'
services:
  php:
    image: yiisoftware/yii2-php:7.1-apache
    container_name: g-api-app
    volumes:
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      - ./:/app:delegated
    ports:
      - '8000:80'
    networks:
      - skynet
  db:
    image: mysql
    container_name: g-api-db
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      - ~/mysql/:/var/lib/mysql
    networks:
      - skynet
    environment:
      MYSQL_ROOT_PASSWORD: root
networks:
    skynet:
        external:
            name: skynet